controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_student_add_grade:
    path: /student/{id}/add-grade
    controller: App\Controller\StudentController::addGrade
